djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView, DashboardView
from django.views.generic.base import RedirectView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('favicon.ico', favicon_view),
    path("", LandingPageView.as_view(), name="landing-page"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("signup", SignupView.as_view(), name="signup"),
    path("password-reset/", PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    FollowUpCreateView,
    FollowUpUpdateView,
    FollowUpDeleteView,
)

app_name = "leads"

urlpatterns = [
    path("", LeadListView.as_view(), name="lead-list"),
    path("<int:pk>/", LeadDetailView.as_view(), name="lead-detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead-update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead-delete"),
    path("<int:pk>/assign-agent/", AssignAgentView.as_view(), name="assign-agent"),
    path("<int:pk>/category/", LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path("<int:pk>/followups/create/", FollowUpCreateView.as_view(), name="lead-followup-create"),
    path("followups/<int:pk>/", FollowUpUpdateView.as_view(), name="lead-followup-update"),
    path("followups/<int:pk>/delete/", FollowUpDeleteView.as_view(), name="lead-followup-delete"),
    path("create/", LeadCreateView.as_view(), name="lead-create"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-detail"),
]

leads/forms.py
from django import forms
from .models import Category, Lead, Agent, FollowUp
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField


User = get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "first_name",
            "last_name",
            "age",
            "agent",
            "description",
            "phone_number",
            "email",
            "profile_picture",
        )

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super().__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super().__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("category",)

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        user = request.user
        queryset = Category.objects.filter(organization=user.userprofile)
        super().__init__(*args, **kwargs)
        self.fields["category"].queryset = queryset
        

class FollowUpModelForm(forms.ModelForm):
    class Meta:
        model = FollowUp
        fields = (
            "notes",
            "file"
        )

leads/views.py
from django.contrib import messages
import datetime
from django.utils import timezone
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from .models import Lead, Category, FollowUp
from .forms import (
    LeadModelForm,
    CustomUserCreationForm,
    AssignAgentForm,
    LeadCategoryUpdateForm,
    FollowUpModelForm
)
from django.views import generic
from agents.mixins import OrganizerLoginRequiredMixin


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(generic.TemplateView):
    template_name = "landing.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("dashboard")
        return super().dispatch(request, *args, **kwargs)


class DashboardView(OrganizerLoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        # How many leads we have in total
        total_lead_count = Lead.objects.filter(organization=user.userprofile).count()

        # How many new leads in the last 30 days
        thirty_days_ago = timezone.now() - datetime.timedelta(days=30)
        total_in_past30 = Lead.objects.filter(
                    organization=user.userprofile, 
                    date_added__gte=thirty_days_ago).count()
                    
        # How many converted leads in the last 30 days
        converted_category = Category.objects.get(organization=user.userprofile, name="Converted")
        print(converted_category)
        converted_in_last30 = Lead.objects.filter(
                    organization=user.userprofile, 
                    category=converted_category,
                    converted_date__gte=thirty_days_ago).count()
        print(converted_in_last30)

        context.update({
                "total_lead_count": total_lead_count,
                "total_in_past30": total_in_past30,
                "converted_in_last30": converted_in_last30,
        })
        return context


class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/lead_list.html"
    context_object_name = "leads"
    
    # initial queryset of leads for the enire organization
    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, agent__isnull=False

            )
            queryset = queryset.exclude(
                category__name="Unassigned"
                
            )
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
            queryset = Lead.objects.exclude(
                category__name="Unassigned"
                
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            unassigned_leads = Lead.objects.filter(
                category=Category.objects.get(organization=user.userprofile, name="Unassigned")
            )
            new_leads = Lead.objects.filter(
                category=Category.objects.get(organization=user.userprofile, name="New")
            )
            context.update({
                "unassigned_leads": unassigned_leads,
                "new_leads": new_leads,
                })
        return context


class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"

    # initial queryset of leads for the enire organization
    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset


class LeadCreateView(OrganizerLoginRequiredMixin, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs.update({"request": self.request})
        return kwargs

    def get_success_url(self) -> str:
        return reverse("leads:lead-list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organization = self.request.user.userprofile
        if lead.agent and (lead.category == None):
            categoty_instanse_id = Category.objects.get(
                name="New", organization=lead.organization
            )
            lead.category = categoty_instanse_id
        else:
            categoty_instanse_id = Category.objects.get(
                name="Unassigned", organization=lead.organization
            )
            lead.category = categoty_instanse_id
        lead.save()

        
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see a new lead",
            from_email="test@test.com",
            recipient_list=["test2@test.com"],
        )
        messages.success(self.request, "You have successfully created a lead!")
        return super(LeadCreateView, self).form_valid(form)


class LeadUpdateView(OrganizerLoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs.update({"request": self.request})
        return kwargs

    # initial queryset of leads for the enire organization
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organization=user.userprofile)

    def get_success_url(self) -> str:
        return reverse("leads:lead-list")

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated a lead")
        return super().form_valid(form)


class LeadDeleteView(OrganizerLoginRequiredMixin, generic.DeleteView):
    template_name = "leads/lead_delete.html"

    def get_success_url(self) -> str:
        return reverse("leads:lead-list")

    # initial queryset of leads for the enire organization
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organization=user.userprofile)


class AssignAgentView(OrganizerLoginRequiredMixin, generic.FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs.update({"request": self.request})
        return kwargs

    def get_success_url(self) -> str:
        return reverse("leads:lead-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        user = self.request.user
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.category = Category.objects.get(organization=user.userprofile, name="New")
        lead.save()
        return super().form_valid(form)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile,
            )

        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)

        contex.update(
            {
                "new": queryset.filter(category__name__iexact="New").count(),
                "unassigned": queryset.filter(
                    category__name__iexact="Unassigned"
                ).count(),
                "contacted": queryset.filter(
                    category__name__iexact="Contacted"
                ).count(),
                "converted": queryset.filter(
                    category__name__iexact="Converted"
                ).count(),
                "unconverted": queryset.filter(
                    category__name__iexact="Unconverted"
                ).count(),
            }
        )
        return contex

    # initial queryset of leads for the enire organization
    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile,
            )
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)
        return queryset


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_detail.html"
    contex_object_name = "category"

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile,
            )
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)
        return queryset


class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm
    model = Lead

    def get_form_kwargs(self, **kwargs):

leads/templates/leads/lead_category_update.html
{% extends 'base.html' %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-1/2 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <div class="w-full flex items-center justify-between space-x-8">
          <div class="flex-1 truncate">
            <div class="flex items-center space-x-3">

              <h3 class="text-3xl text-gray-800 font-medium truncate">{{ lead.first_name }} {{ lead.last_name }}
              </h3>
            </div>
            <p class="mt-1 mb-3 text-xl text-gray-500 truncate">{{ lead.description }}</p>


          </div>
          <img class="inline object-cover w-16 h-16 mr-2 rounded-full" src="{{ lead.profile_picture.url }}" alt="">
        </div>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead-detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
          <a href="{% url 'leads:lead-category-update' lead.pk %}" class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            ">Category</a>
          {% if request.user.is_organizer %}
          <a href="{% url 'leads:lead-update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
          {% endif %}
        </div>
        <form method="POST" action="">
          {% csrf_token %} {{ form|crispy}}
          <button
            class="w-full text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
            type="submit">
            Submit
          </button>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %} {% block content %}

<div class="container px-5 py-24 mx-auto flex flex-wrap">
  <div class="
        w-full
        mb-6
        py-6
        flex
        justify-between
        items-center
        border-b border-gray-200
      ">
    <div>
      <h1 class="text-4xl text-gray-800">Leads</h1>

    </div>
    {% if request.user.is_organizer %}
    <div>
      <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead-create' %}">Create a new lead</a>
    </div>
    {% endif %}
  </div>
  {% if leads %}
  <table class="min-w-max w-full table-auto">
    <thead>
      <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
        <th class="py-3 px-6 text-left">NAME</th>
        <th class="py-3 px-6 text-center">AGE</th>
        <th class="py-3 px-6 text-center">EMAIL</th>
        <th class="py-3 px-6 text-center">PHONE NUMBER</th>
        <th class="py-3 px-6 text-center">STATUS</th>
        <th class="py-3 px-6 text-center">ACTIONS</th>
      </tr>
    </thead>
    <tbody class="text-gray-600 text-sm font-light">
      {% endif %}
      {% for lead in leads|dictsort:"first_name" %}
      <tr class="border-b border-gray-200 hover:bg-gray-100">
        <td class="py-3 px-6 text-left">
          <div class="flex items-center">
            <div class="mr-2">
              <img class="w-12 h-12 rounded-full" src={{ lead.profile_picture.url }} alt="" />
            </div>
            <a class="text-blue-500 hover:text-blue-800" href="{% url 'leads:lead-detail' lead.pk %}">
              <span class="font-medium">{{ lead.first_name }} {{ lead.last_name }}</span></a>
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex items-center justify-center">
            {{ lead.age }}
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex items-center justify-center">
            {{ lead.email }}
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex items-center justify-center">
            {{ lead.phone_number }}
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          {% if lead.category|stringformat:"s" == "New"%}
          <span class="bg-blue-200 text-blue-600 py-1 px-3 rounded-full text-xs">New</span>
          {% elif lead.category|stringformat:"s" == "Contacted"%}
          <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">Contacted</span>
          {% elif lead.category|stringformat:"s" == "Converted"%}
          <span class="bg-green-200 text-green-600 py-1 px-3 rounded-full text-xs">Converted</span>
          {% elif lead.category|stringformat:"s" == "Unconverted"%}
          <span class="bg-red-200 text-red-600 py-1 px-3 rounded-full text-xs">Unconverted</span>



          {% endif %}
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex item-center justify-center">
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'leads:lead-detail' lead.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </svg></a>
            </div>
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'leads:lead-category-update' lead.pk %}"><svg xmlns="http://www.w3.org/2000/svg"
                  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"></path>
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"></path>
                </svg></a>
            </div>
            {% if request.user.is_organizer %}
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'leads:lead-update' lead.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </a>
              </svg>
            </div>
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'leads:lead-delete' lead.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg></a>
              {% endif %}
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>

  {% if unassigned_leads.exists %}
  <div class="w-full mb-6 py-6 flex justify-between items-center
        border-b border-gray-200">
    <div class="mt-10">
      <h1 class="text-4xl text-gray-800">Unassigned leads</h1>

    </div>
  </div>
  <table class="min-w-max w-full table-auto">
    <thead>
      <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
        <th class="py-3 px-6 text-left">NAME</th>
        <th class="py-3 px-6 text-center">AGE</th>
        <th class="py-3 px-6 text-center">EMAIL</th>
        <th class="py-3 px-6 text-center">PHONE NUMBER</th>
        <th class="py-3 px-6 text-center">STATUS</th>
        <th class="py-3 px-6 text-center">ACTIONS</th>
      </tr>
    </thead>
    <tbody class="text-gray-600 text-sm font-light">
      {% for lead in unassigned_leads %}
      <tr class="border-b border-gray-200 hover:bg-gray-100">
        <td class="py-3 px-6 text-left">
          <div class="flex items-center">
            <div class="mr-2">
              <img class="w-12 h-12 rounded-full" src={{ lead.profile_picture.url }} alt="" />
            </div>
            <a class="text-blue-500 hover:text-blue-800" href="{% url 'leads:lead-detail' lead.pk %}"><span
                class="font-medium">{{ lead.first_name }} {{ lead.last_name }}</span></a>
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex items-center justify-center">
            {{ lead.age }}
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex items-center justify-center">
            {{ lead.email }}
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex items-center justify-center">
            {{ lead.phone_number }}
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <span class="bg-yellow-200 text-yellow-600 py-1 px-3 rounded-full text-xs">Unassigned</span>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex item-center justify-center">
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'leads:lead-detail' lead.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </svg></a>
            </div>
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'leads:assign-agent' lead.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"></path>
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"></path>
                </svg></a>
            </div>
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'leads:lead-update' lead.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </a>
              </svg>
            </div>
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'leads:lead-delete' lead.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg></a>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
      {% endif %}

    </tbody>
  </table>
</div>
</div>

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-1/2 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <div class="w-full flex items-center justify-between space-x-8">
          <div class="flex-1 truncate">
            <div class="flex items-center space-x-3">
              <h3 class="text-3xl text-gray-800 font-medium truncate">{{ lead.first_name }} {{ lead.last_name }}
              </h3>
            </div>
            <p class="mt-1 mb-3 text-xl text-gray-500 truncate">{{ lead.description }}</p>
          </div>
          <img class="inline object-cover w-16 h-16 mr-2 rounded-full" src="{{ lead.profile_picture.url }}" alt="">
        </div>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead-detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
          <a href="{% url 'leads:lead-category-update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead-update' lead.pk %}" class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            ">Update Details</a>
        </div>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{ form|crispy }}
          <button
            class="w-full text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
            type="submit">
            Submit
          </button>
        </form>

      </div>
    </div>
  </div>
</section>

{% endblock content %}