agents/urls.py
from django.urls import path
from .views import (
    AgentListView,
    AgentCreateView,
    AgentDetailView,
    AgentUpdateView,
    AgentDeleteView,
)


app_name = "agents"

urlpatterns = [
    path("", AgentListView.as_view(), name="agent-list"),
    path("<int:pk>/", AgentDetailView.as_view(), name="agent-detail"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="agent-update"),
    path("<int:pk>/delete", AgentDeleteView.as_view(), name="agent-delete"),
    path("create/", AgentCreateView.as_view(), name="agent-create"),
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView, DashboardView
from django.views.generic.base import RedirectView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('favicon.ico', favicon_view),
    path("", LandingPageView.as_view(), name="landing-page"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("signup", SignupView.as_view(), name="signup"),
    path("password-reset/", PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "email",
            "username",
            "first_name",
            "last_name",
            "user_picture",
            
        )

agents/views.py
import random
from django.contrib import messages
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganizerLoginRequiredMixin
from django.core.mail import send_mail


class AgentListView(OrganizerLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        request_user_organization = self.request.user.userprofile
        return Agent.objects.filter(organization=request_user_organization)


class AgentCreateView(OrganizerLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organizer = False
        user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        Agent.objects.create(user=user, organization=self.request.user.userprofile)
        send_mail(
            subject="You are invited to be an agent",
            message="You were added as an agent on DJCRM. Please come login to start working.",
            from_email="admin@test.com",
            recipient_list=[user.email],
        )
        messages.success(self.request, "You have successfully created an agent!")
        return super().form_valid(form)


class AgentDetailView(OrganizerLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        request_user_organization = self.request.user.userprofile
        return Agent.objects.filter(organization=request_user_organization)


class AgentUpdateView(OrganizerLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_queryset(self):
        request_user_organization = self.request.user.userprofile
        return Agent.objects.filter(organization=request_user_organization)

    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated an agent!")
        return super().form_valid(form)


class AgentDeleteView(OrganizerLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"

    def get_queryset(self):
        request_user_organization = self.request.user.userprofile
        return Agent.objects.filter(organization=request_user_organization)

    def get_success_url(self):
        return reverse("agents:agent-list")

        

agents/templates/agents/agent_create.html
{% extends 'base.html' %} {% load tailwind_filters %} {% block content %}
<div class="max-w-lg mx-auto">
  <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}">Go back to agents</a>
  <hr />
  <div class="py-5 border-t border-gray-200">
    <h1 class="text-3xl text-gray-800">Create a new agent</h1>
  </div>
  <form method="POST" action="" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button type="submit"
      class="w-full text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
      Submit
    </button>
  </form>
</div>
{% endblock %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %} {% load tailwind_filters %} {% block content %}
<div class="max-w-lg mx-auto">
  <div class="py-5 mt-5 border-b border-gray-200">
    <a class="hover:text-blue-500 mt-3" href="{% url 'agents:agent-list' %}">Go back to agents</a>
  </div>

  <h1 class="text-3xl text-center text-gray-800">
    Are you sure you want to delete this agent?
  </h1>
  <form method="POST" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button
      class="w-full text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
      type="submit">
      Submit
    </button>
  </form>
</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends 'base.html' %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-1/2 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <div class="w-full flex items-center justify-between space-x-8">
          <div class="flex-1 truncate">
            <div class="flex items-center space-x-3">
              <h3 class="text-3xl text-gray-800 font-medium truncate pb-5">{{ agent.user.first_name }}
                {{ agent.user.last_name }}
              </h3>
            </div>
            <p class="mt-1 mb-3 text-xl text-gray-500 truncate">{{ agent.description }}</p>
          </div>
          <img class="inline object-cover w-16 h-16 mr-2 rounded-full" src="{{ agent.user.user_picture.url }}" alt="">
        </div>
        <div class="flex mb-4">
          <a href="{% url 'agents:agent-detail' agent.pk %}" class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            ">Overview</a>
          <a href="{% url 'agents:agent-update' agent.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
        </div>
        <p class="text-xl leading-relaxed mb-4">{{ agent.description }}</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">First name</span>
          <span class="ml-auto text-gray-900">{{ agent.user.first_name }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Last name</span>
          <span class="ml-auto text-gray-900">{{ agent.user.last_name }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
        </div>


      </div>

    </div>
  </div>
</section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %} {% block content %}

<div class="container px-5 py-24 mx-auto flex flex-wrap">
  <div class="
        w-full
        mb-6
        py-6
        flex
        justify-between
        items-center
        border-b border-gray-200
      ">
    <div>
      <h1 class="text-4xl text-gray-800">Agents</h1>

    </div>
    <div>
      <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Create a new Agent</a>
    </div>
  </div>
  {% if object_list %}
  <table class="min-w-max w-full table-auto">
    <thead>
      <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
        <th class="py-3 px-6 text-left">NAME</th>
        <th class="py-3 px-6 text-center">EMAIL</th>
        <th class="py-3 px-6 text-center">ACTIONS</th>
      </tr>
    </thead>
    <tbody class="text-gray-600 text-sm font-light">

      {% for agent in object_list %}
      <tr class="border-b border-gray-200 hover:bg-gray-100">
        <td class="py-3 px-6 text-left">
          <div class="flex items-center">
            <div class="mr-2">
              <img class="w-12 h-12 rounded-full" src={{  agent.user.user_picture.url }} alt="" />
            </div>
            <a class="text-blue-500 hover:text-blue-800" href="{% url 'agents:agent-detail' agent.pk %}">
              <span class="font-medium">{{ agent.user.first_name }} {{ agent.user.last_name }}</span></a>
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex items-center justify-center">
            {{ agent.user.email }}
          </div>
        </td>
        <td class="py-3 px-6 text-center">
          <div class="flex item-center justify-center">
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'agents:agent-detail' agent.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </svg></a>
            </div>
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'agents:agent-update' agent.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </a>
              </svg>
            </div>
            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
              <a href="{% url 'agents:agent-delete' agent.pk %}"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg></a>
            </div>

          </div>
        </td>
      </tr>
      {% endfor %}
      {% endif %}

    </tbody>
  </table>



  {% endblock content %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-1/2 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <div class="w-full flex items-center justify-between space-x-8">
          <div class="flex-1 truncate">
            <div class="flex items-center space-x-3">
              <h3 class="text-3xl text-gray-800 font-medium truncate pb-5">{{ agent.user.first_name }}
                {{ agent.user.last_name }}
              </h3>
            </div>
            <p class="mt-1 mb-3 text-xl text-gray-500 truncate">{{ agent.description }}</p>
          </div>
          <img class="inline object-cover w-16 h-16 mr-2 rounded-full" src="{{ agent.user.user_picture.url }}" alt="">
        </div>
        <div class="flex mb-4">
          <a href="{% url 'agents:agent-detail' agent.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
          <a href="{% url 'agents:agent-update' agent.pk %}" class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            ">Update Details</a>
        </div>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{ form|crispy }}
          <button
            class="w-full text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
            type="submit">
            Submit
          </button>
        </form>

      </div>
    </div>
  </div>
</section>
{% endblock content %}