agents/urls.py
from django.urls import path
from .views import (
    AgentListView,
    AgentCreateView,
    AgentDetailView,
    AgentUpdateView,
    AgentDeleteView,
)


app_name = "agents"

urlpatterns = [
    path("", AgentListView.as_view(), name="agent-list"),
    path("<int:pk>/", AgentDetailView.as_view(), name="agent-detail"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="agent-update"),
    path("<int:pk>/delete", AgentDeleteView.as_view(), name="agent-delete"),
    path("create/", AgentCreateView.as_view(), name="agent-create"),
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView, DashboardView
from django.views.generic.base import RedirectView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('favicon.ico', favicon_view),
    path("", LandingPageView.as_view(), name="landing-page"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("signup", SignupView.as_view(), name="signup"),
    path("password-reset/", PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    FollowUpCreateView,
    FollowUpUpdateView,
    FollowUpDeleteView,
)

app_name = "leads"

urlpatterns = [
    path("", LeadListView.as_view(), name="lead-list"),
    path("<int:pk>/", LeadDetailView.as_view(), name="lead-detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead-update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead-delete"),
    path("<int:pk>/assign-agent/", AssignAgentView.as_view(), name="assign-agent"),
    path("<int:pk>/category/", LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path("<int:pk>/followups/create/", FollowUpCreateView.as_view(), name="lead-followup-create"),
    path("followups/<int:pk>/", FollowUpUpdateView.as_view(), name="lead-followup-update"),
    path("followups/<int:pk>/delete/", FollowUpDeleteView.as_view(), name="lead-followup-delete"),
    path("create/", LeadCreateView.as_view(), name="lead-create"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-detail"),
]

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DJ-CRM</title>
  {% tailwind_css %}
  <link rel="icon" href="{% static 'img/favicon.ico' %}">
</head>

<body>
  <div class="max-w-7xl mx-auto">
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% block content %}
    {% endblock content %}
  </div>
  {% include "scripts.html" %}
</body>

</html>

templates/dashboard.html
{% extends 'base.html' %} {% block content %} {% load static %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <div class="text-center lg:w-2/3 w-full">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                CRM Dashboard
            </h1>


            <div class="flex flex-wrap -m-4 text-center">
                <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                    <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                            <path d="M8 17l4 4 4-4m-4-5v9"></path>
                            <path d="M20.88 18.09A5 5 0 0018 9h-1.26A8 8 0 103 16.29"></path>
                        </svg>
                        <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_lead_count }}</h2>
                        <p class="leading-relaxed">Total Leads</p>
                    </div>
                </div>
                <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                    <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                            <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"></path>
                            <circle cx="9" cy="7" r="4"></circle>
                            <path d="M23 21v-2a4 4 0 00-3-3.87m-4-12a4 4 0 010 7.75"></path>
                        </svg>
                        <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_in_past30 }}</h2>
                        <p class="leading-relaxed">Leads added in last 30 days</p>
                    </div>
                </div>
                <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                    <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                            <path d="M3 18v-6a9 9 0 0118 0v6"></path>
                            <path
                                d="M21 19a2 2 0 01-2 2h-1a2 2 0 01-2-2v-3a2 2 0 012-2h3zM3 19a2 2 0 002 2h1a2 2 0 002-2v-3a2 2 0 00-2-2H3z">
                            </path>
                        </svg>
                        <h2 class="title-font font-medium text-3xl text-gray-900">{{ converted_in_last30 }}</h2>
                        <p class="leading-relaxed">Converted in last 30 days</p>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>
{% endblock content %}

templates/landing.html
{% extends 'base.html' %} {% block content %} {% load static %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded-xl" alt="hero"
      src="{% static 'img/landing.png' %}" />
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
        CRM built with Django
      </h1>
      <p class="mb-8 leading-relaxed">CRM helps you manage your leads.</p>
      <div class="flex justify-center">
        <a href="{% url 'login' %}"><button
            class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
            Get Started
          </button></a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="p-4 border-l-4
        {% if message.tags == 'success' %}
        bg-green-50 border-green-400
        {% elif message.tags == 'info' %}
        bg-blue-50 border-blue-400
        {% elif message.tags == 'warning' %}
        bg-yellow-50 border-yellow-400
        {% else %}
        bg-red-50 border-red-400
        {% endif %}
        ">
  <p class="text-sm
            {% if message.tags == 'success' %}
            text-green-700
            {% elif message.tags == 'info' %}
            text-blue-700
            {% elif message.tags == 'warning' %}
            text-yellow-700
            {% else %}
            text-red-700
            {% endif %}
            ">
    {{ message }}
  </p>
</div>
{% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<header class="text-gray-600 body-font">
  <div class="
      container
      mx-auto
      flex flex-wrap
      p-5
      flex-col
      md:flex-row
      items-center
    ">
    <a href="{% url 'landing-page' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"><span
        class="ml-3 text-xl text-gray-500">DJ-</span>
      <div>
        <img class="w-10" src="{% static 'img/icon.png' %}" />
      </div>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if not request.user.is_authenticated %}
      <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign up</a>
      {% else %} {% if request.user.is_organizer %}
      <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
      {% endif %}
      <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
      <a href="{% url 'leads:category-list' %}" class="mr-5 hover:text-gray-900">
        Categories</a>
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %} Logged in as: {{ request.user.username }}
    <a href="{% url 'logout' %}" class="
        ml-3
        inline-flex
        items-center
        bg-gray-100
        border-0
        py-1
        px-3
        focus:outline-none
        hover:bg-gray-200
        rounded
        text-base
        mt-4
        md:mt-0
      ">Logout
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else %}
    <a href="{% url 'login' %}" class="
        inline-flex
        items-center
        bg-gray-100
        border-0
        py-1
        px-3
        focus:outline-none
        hover:bg-gray-200
        rounded
        text-base
        mt-4
        md:mt-0
      ">Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>